# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0002_auto_20190811_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identity',
            new_name='ID',
        ),
    ]
